option(SENTIENT_C_USE_OS "using OS/RTOS in sentient" ON)

option(SENTIENT_C_USE_HEAP "using object heap allocations" OFF)
option(SENTIENT_C_USE_POOL "using object pool allocations" ON)
if (SENTIENT_C_USE_HEAP)
    set(SENTIENT_C_USE_POOL OFF)
endif()
if (SENTIENT_C_USE_POOL)
    set(SENTIENT_C_USE_HEAP OFF)
    set(SENTIENT_C_NUM_POOL_LOOP 5)
endif()

if (SENTIENT_C_USE_OS)
option(SENTIENT_C_OS_POSIX "using POSIX" ON)
option(SENTIENT_C_OS_ZEPHYR "using Zephyr RTOS" OFF)
option(SENTIENT_C_OS_RIOT "using RIOT" OFF)
option(SENTIENT_C_OS_MIPOS "using MIPOS" OFF)
option(SENTIENT_C_OS_MYNEWT "using Mynewt" OFF)
endif()

if (SENTIENT_C_USE_OS)
    if (SENTIENT_C_OS_POSIX)
        set(SENTIENT_C_OS_ZEPHYR OFF)
        set(SENTIENT_C_OS_RIOT OFF)
        set(SENTIENT_C_OS_MIPOS OFF)
        set(SENTIENT_C_OS_MYNEWT OFF)
    endif()
    if (SENTIENT_C_OS_ZEPHYR)
        set(SENTIENT_C_OS_POSIX OFF)
        set(SENTIENT_C_OS_RIOT OFF)
        set(SENTIENT_C_OS_MIPOS OFF)
        set(SENTIENT_C_OS_MYNEWT OFF)
    endif()
    if (SENTIENT_C_OS_RIOT)
        set(SENTIENT_C_OS_POSIX OFF)
        set(SENTIENT_C_OS_ZEPHYR OFF)
        set(SENTIENT_C_OS_MYNEWT OFF)
        set(SENTIENT_C_OS_MIPOS OFF)
    endif()
    if (SENTIENT_C_OS_MYNEWT)
        set(SENTIENT_C_OS_POSIX OFF)
        set(SENTIENT_C_OS_ZEPHYR OFF)
        set(SENTIENT_C_OS_RIOT OFF)
        set(SENTIENT_C_OS_MIPOS OFF)
    endif()
    if (SENTIENT_C_OS_MIPOS)
        set(SENTIENT_C_OS_POSIX OFF)
        set(SENTIENT_C_OS_ZEPHYR OFF)
        set(SENTIENT_C_OS_RIOT OFF)
        set(SENTIENT_C_OS_MYNEWT OFF)
    endif()

endif()
